// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKCdEbjzRNTpxEiXhgXKleizTxvLC__o',
    appId: '1:471816249462:web:659759dfc7a4936f993f57',
    messagingSenderId: '471816249462',
    projectId: 'busbuddy-33f8e',
    authDomain: 'busbuddy-33f8e.firebaseapp.com',
    storageBucket: 'busbuddy-33f8e.firebasestorage.app',
    measurementId: 'G-V43G02ZE7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdoo1R3UCcaRlIymUDP0QRfSz8EajWGk',
    appId: '1:471816249462:android:d6796f4f56ed3a90993f57',
    messagingSenderId: '471816249462',
    projectId: 'busbuddy-33f8e',
    storageBucket: 'busbuddy-33f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVr7Mp5ofuV_2WOgzHhOHoQfpDXZ5xwo',
    appId: '1:471816249462:ios:698ad841c20ea8a1993f57',
    messagingSenderId: '471816249462',
    projectId: 'busbuddy-33f8e',
    storageBucket: 'busbuddy-33f8e.firebasestorage.app',
    iosBundleId: 'com.example.diubusbuddy',
  );
}
